[tool.poetry]
name = "project5"
version = "0.1.0"
description = ""
authors = ["Anton Masloynok <antoxa.toxa.83@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
